version: '2'

services:

  session:
    image: redis
    ports:
      - '9001:6379'
    volumes:
      - session-db-storage:/data
    networks:
      - network

  database:
    image: mysql
    ports:
      - '9002:3306'
    volumes:
      - app-db-storage:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: expressJsTemplate

  api:
    image: node
    ports:
      - '9003:3000'
      - '9004:5858'
    volumes:
      - .:/app
      - app-storage:/upload
    networks:
      - network
    working_dir: /app
    command: npm run serve
    environment:
      NODE_ENV: development
      PORT: 3000
      SDB_PROTOCOL: redis
      SDB_HOST: session
      SDB_PORT: 6379
      ADB_PROTOCOL: mysql
      ADB_HOST: database
      ADB_PORT: 3306
      ADB_USERNAME: root
      ADB_PASSWORD:
      ADB_NAME: expressJsTemplate
      SALT: '__SALT__'
      SECRET_KEY: '__SECRET_KEY__'
    depends_on:
      - session
      - database

volumes:
  session-db-storage:
  app-db-storage:
  app-storage:

networks:
  network:
