version: '2'

services:

  session-database:
    image: redis
    ports:
      - '3100:6379'
    volumes:
      - session-db-storage:/data
    networks:
      - back-tire

  app-database:
    image: mysql
    ports:
      - '3200:3306'
    volumes:
      - app-db-storage:/var/lib/mysql
    networks:
      - back-tire
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: expressJsTemplate

  api-server:
    image: node
    ports:
      - '3000:3000'
      - '3300:5858'
    volumes:
      - .:/app
      - app-storage:/upload
    networks:
      - back-tire
      - front-tire
    working_dir: /app
    command: npm run serve
    environment:
      NODE_ENV: development
      PORT: 3000
      SDB_PROTOCOL: redis
      SDB_HOST: session-database
      SDB_PORT: 6379
      ADB_PROTOCOL: mysql
      ADB_HOST: app-database
      ADB_PORT: 3306
      ADB_USERNAME: root
      ADB_PASSWORD:
      ADB_NAME: expressJsTemplate
      SALT: '__SALT__'
      SECRET_KEY: '__SECRET_KEY__'
    depends_on:
      - session-database
      - app-database

  static-server:
    image: node
    volumes:
      - .:/app
      - app-storage:/upload
#    networks:
#      - front-tire
    ports:
      - '3400:3000'
      - '3500:5858'
    working_dir: /app
    command: npm run serve-static
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - api-server

volumes:
  session-db-storage:
  app-db-storage:
  app-storage:

networks:
  front-tire:
  back-tire:
